// src/features/booking/components/BookingForm.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { actions } from "astro:actions";
import { TOURS_DATA } from "@/features/tours/data/toursData";
import { hasRecaptchaV2, RECAPTCHA_V2_SITE_KEY } from "@/lib/client-env";
import type { FormState } from "@/lib/form-types";
import { useTranslation } from "@/lib/hooks/useTranslation";
import Loading from "@/shared/ui/Loading.vue";
import Recaptcha from "@/shared/ui/Recaptcha.vue";
import BookingFormFields from "./BookingFormFields.vue";
import BookingSidebar from "./BookingSidebar.vue";
import FormStatusMessages from "./FormStatusMessages.vue";

interface Props {
  tourTitle?: string;
  tourId?: string;
  excursionTitle?: string;
  excursionId?: string;
  fullWidth?: boolean;
}

const props = withDefaults(defineProps<Props>(), { fullWidth: false });

const { t, i18n } = useTranslation();
const recaptchaRef = ref<InstanceType<typeof Recaptcha> | null>(null);

const formKey = ref(0);
const calendarOpen = ref(false);
const reservationDate = ref<Date | null>(null);
const captchaToken = ref("");
const buttonText = ref("booking.checkAvailability");
const state = ref<FormState | null>(null);
const isSubmitting = ref(false);

const handleVerify = (token: string) => {
  captchaToken.value = token;
};

const handleExpired = () => {
  captchaToken.value = "";
};

const perks = computed(() => [
  { id: "experts", text: t("booking.perkLocalExperts", "Licensed local drivers & guides") },
  { id: "flexible", text: t("booking.perkFlexible", "Flexible departures from Marrakech") },
  { id: "support", text: t("booking.perkSupport", "Fast responses within 24 hours") },
]);

const selectedTour = computed(() => {
  if (props.tourTitle && props.tourId) {
    const tour = TOURS_DATA.find((t) => t.id === Number(props.tourId));
    return `${props.tourTitle} - Duration: ${tour?.duration || ""} Days`;
  }
  return props.tourTitle || props.excursionTitle || "";
});

const tourDuration = computed(() => {
  if (props.tourId) {
    return TOURS_DATA.find((t) => t.id === Number(props.tourId))?.duration ?? null;
  }
  return null;
});

const handleSubmit = async (event: Event) => {
  const form = event.target as HTMLFormElement;
  const formData = new FormData(form);
  const fullName = formData.get("fullName") as string;
  const email = formData.get("email") as string;

  if (!fullName.trim() || !email.trim() || isSubmitting.value) return;

  const recaptchaToken = recaptchaRef.value?.getValue() ?? "";
  if (!recaptchaToken) {
    state.value = {
      success: false,
      message: t("booking.errors.captcha", "Recaptcha verification is required"),
      errors: { recaptchaToken: t("booking.errors.captcha", "Recaptcha verification is required") },
    };
    return;
  }
  formData.set("recaptchaToken", recaptchaToken);

  isSubmitting.value = true;
  state.value = null;

  try {
    const { data, error } = await actions.booking(formData);

    if (error) {
      state.value = {
        success: false,
        message: error.message || "Booking submission failed",
        errors: {},
      };
      recaptchaRef.value?.reset();
      captchaToken.value = "";
    } else if (data) {
      state.value = data;
      if (data.success) {
        buttonText.value = "Your booking request has been sent";
        reservationDate.value = null;
        captchaToken.value = "";

        setTimeout(() => {
          formKey.value += 1;
          buttonText.value = "booking.checkAvailability";
        }, 4000);
      } else {
        recaptchaRef.value?.reset();
        captchaToken.value = "";
        setTimeout(() => {
          const firstError = document.querySelector('[aria-invalid="true"]');
          firstError?.scrollIntoView({ behavior: "smooth", block: "center" });
        }, 50);
      }
    }
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Booking submission failed";
    state.value = { success: false, message, errors: {} };
    recaptchaRef.value?.reset();
    captchaToken.value = "";
  } finally {
    isSubmitting.value = false;
  }
};
</script>

<template>
  <section
    id="booking"
    aria-labelledby="booking-heading"
    :class="['bg-neutral-50 py-20 md:py-10', fullWidth ? 'booking-form-fullwidth' : '']"
  >
    <div
      :class="[
        'booking-form-inner mx-auto overflow-x-hidden inline-full max-inline-6xl',
        fullWidth ? 'px-4 sm:px-6 lg:px-10' : 'px-4 sm:px-6 lg:px-8',
      ]"
    >
      <div class="grid grid-cols-1 gap-8 lg:grid-cols-5">
        <div
          class="inline-full lg:col-span-3"
          data-animate="creative-slide-right"
        >
          <div class="overflow-hidden rounded-3xl bg-white block-full">
            <div class="bg-linear-to-r from-orange-500 to-orange-600 px-6 py-8 text-white">
              <h2
                id="booking-heading"
                class="text-xl font-semibold sm:text-2xl md:text-3xl"
              >
                {{ t("booking.makeReservation", "Make your reservation") }}
              </h2>
              <p class="mbs-3 text-sm text-orange-50/90 md:text-base">
                {{ t("booking.description", "Book your perfect Morocco adventure with us") }}
              </p>
            </div>

            <form
              :key="formKey"
              class="space-y-5 p-6 md:p-8"
              noValidate
              data-form="booking"
              @submit.prevent="handleSubmit"
            >
              <FormStatusMessages
                v-bind="{
                  ...(state?.['errors']?.['submit'] ?
                    { submitError: state['errors']['submit'] }
                  : {}),
                  ...(state?.['success'] !== undefined ? { success: state['success'] } : {}),
                  ...(state?.['message'] ? { successMessage: state['message'] } : {}),
                }"
              />

              <!-- Honeypot -->
              <div
                aria-hidden="true"
                class="absolute -left-2499.75 h-0 overflow-hidden"
              >
                <input
                  type="text"
                  name="website"
                  tabindex="-1"
                  autocomplete="off"
                  aria-label="Leave this field empty"
                />
              </div>

              <BookingFormFields
                v-model:calendar-open="calendarOpen"
                v-model:reservation-date="reservationDate"
                :state="state"
                :selected-tour="selectedTour"
                v-bind="{
                  ...(tourTitle ? { tourTitle } : {}),
                  ...(tourId ? { tourId } : {}),
                  ...(excursionTitle ? { excursionTitle } : {}),
                  ...(excursionId ? { excursionId } : {}),
                }"
                :tour-duration="tourDuration"
                :locale="i18n.language"
              />

              <div class="flex flex-col gap-4 lg:flex-row lg:items-center">
                <div class="flex justify-center inline-full lg:justify-start">
                  <div
                    :class="[
                      'w-fit origin-center scale-85 rounded-2xl border border-dashed p-3 transition-all duration-500 sm:scale-100',
                      state?.['errors']?.['recaptchaToken'] ?
                        'border-red-300'
                      : 'border-neutral-200',
                    ]"
                  >
                    <Recaptcha
                      v-if="hasRecaptchaV2"
                      ref="recaptchaRef"
                      :sitekey="RECAPTCHA_V2_SITE_KEY"
                      @verify="handleVerify"
                      @expired="handleExpired"
                    />
                    <div
                      v-else
                      class="rounded-lg bg-amber-50 p-2 text-sm text-amber-600"
                    >
                      reCAPTCHA not configured
                    </div>
                  </div>
                </div>

                <p
                  v-if="state?.['errors']?.['recaptchaToken']"
                  id="recaptchaToken-error"
                  class="mbs-1 text-xs text-red-600"
                >
                  {{ state["errors"]["recaptchaToken"] }}
                </p>

                <button
                  type="submit"
                  class="inline-flex transform items-center justify-center gap-2 rounded-full border border-orange-400 bg-linear-to-r from-orange-500 to-orange-600 px-6 py-3 text-sm font-semibold tracking-wide whitespace-nowrap text-white uppercase transition duration-300 ease-in-out inline-full disabled:cursor-not-allowed disabled:opacity-60 md:inline-auto md:min-inline-50 pointer-fine:hover:-translate-y-0.5 pointer-fine:hover:brightness-110"
                  :disabled="isSubmitting"
                  :aria-busy="isSubmitting"
                >
                  <Loading
                    v-if="isSubmitting"
                    size="sm"
                  />
                  <span>
                    {{
                      isSubmitting ? t("booking.sending", "Sending...")
                      : buttonText === "booking.checkAvailability" ? t(buttonText, "Reserve Now")
                      : buttonText
                    }}
                  </span>
                </button>
              </div>
            </form>
          </div>
        </div>

        <div
          class="inline-full lg:col-span-2 lg:block-full"
          data-animate="creative-slide-left"
          data-delay="150"
        >
          <BookingSidebar :perks="perks" />
        </div>
      </div>
    </div>
  </section>
</template>

// src/features/booking/components/BookingForm.tsx
import { lazy, Suspense, useActionState, useEffect, useReducer, useRef, useState } from "react";
import { withState } from "@astrojs/react/actions";
import { actions } from "astro:actions";
import { useFormStatus } from "react-dom";
import type ReCAPTCHAComponent from "react-google-recaptcha";
import { TOURS_DATA } from "@/features/tours/data/toursData";
import { hasRecaptchaV2, RECAPTCHA_V2_SITE_KEY } from "@/lib/client-env";
import type { FormState } from "@/lib/form-types";
import { useTranslation } from "@/lib/hooks/useTranslation";
import { cn } from "@/lib/utils";
import { LoadingSpinner } from "@/shared/ui/Loading";
import { BookingFormFields } from "./BookingFormFields";
import { BookingSidebar } from "./BookingSidebar";
import { FormStatusMessages } from "./FormStatusMessages";

const ReCAPTCHA = lazy(() => import("react-google-recaptcha"));

type FormUIState = {
  calendarOpen: boolean;
  reservationDate: Date | null;
  captchaToken: string;
  buttonText: string;
};

type FormUIAction =
  | { type: "SET_CALENDAR_OPEN"; open: boolean }
  | { type: "SET_DATE"; date: Date | null }
  | { type: "SET_CAPTCHA"; token: string }
  | { type: "SET_BUTTON_TEXT"; text: string }
  | { type: "RESET_UI_ONLY" };

const initialUIState: FormUIState = {
  calendarOpen: false,
  reservationDate: null,
  captchaToken: "",
  buttonText: "booking.checkAvailability",
};

function formUIReducer(state: FormUIState, action: FormUIAction): FormUIState {
  switch (action.type) {
    case "SET_CALENDAR_OPEN": {
      return { ...state, calendarOpen: action.open };
    }
    case "SET_DATE": {
      return { ...state, reservationDate: action.date };
    }
    case "SET_CAPTCHA": {
      return { ...state, captchaToken: action.token };
    }
    case "SET_BUTTON_TEXT": {
      return { ...state, buttonText: action.text };
    }
    case "RESET_UI_ONLY": {
      return {
        ...state,
        reservationDate: null,
        captchaToken: "",
        buttonText: "Your booking request has been sent",
      };
    }
    default: {
      return state;
    }
  }
}

type BookingFormProperties = {
  tourTitle?: string;
  tourId?: string;
  excursionTitle?: string;
  excursionId?: string;
  fullWidth?: boolean;
};

function SubmitButton({ buttonText }: { buttonText: string }) {
  const { t } = useTranslation();
  const { pending } = useFormStatus();

  return (
    <button
      type="submit"
      className="inline-flex transform items-center justify-center gap-2 rounded-full border border-orange-400 bg-linear-to-r from-orange-500 to-orange-600 px-6 py-3 text-sm font-semibold tracking-wide whitespace-nowrap text-white uppercase transition duration-300 ease-in-out inline-full disabled:cursor-not-allowed disabled:opacity-60 md:inline-auto md:min-inline-50 pointer-fine:hover:-translate-y-0.5 pointer-fine:hover:brightness-110"
      disabled={pending}
      aria-busy={pending}
    >
      {pending ?
        <LoadingSpinner size="sm" />
      : null}
      {pending ?
        t("booking.sending", "Sending...")
      : buttonText === "booking.checkAvailability" ?
        t(buttonText, "Reserve Now")
      : buttonText}
    </button>
  );
}

function BookingForm({
  tourTitle,
  tourId,
  excursionTitle,
  excursionId,
  fullWidth = false,
}: BookingFormProperties) {
  const { t, i18n } = useTranslation();
  const recaptchaReference = useRef<ReCAPTCHAComponent>(null);

  const [formKey, setFormKey] = useState(0);

  const [uiState, dispatch] = useReducer(formUIReducer, initialUIState);

  type AstroActionResult = { data?: FormState; error?: { message: string } };

  const [actionResult, formAction] = useActionState<AstroActionResult | null, FormData>(
    withState(actions.booking) as unknown as (
      state: AstroActionResult | null,
      formData: FormData,
    ) => Promise<AstroActionResult | null>,
    null,
  );

  const state: FormState | null =
    actionResult ?
      actionResult.data ?
        actionResult.data
      : {
          success: false,
          message: actionResult.error?.message || "Booking submission failed",
          errors: {},
        }
    : null;

  const stateReference = useRef(state);
  useEffect(() => {
    stateReference.current = state;
  });

  useEffect(() => {
    const currentState = stateReference.current;
    if (!currentState?.["success"]) return;

    dispatch({ type: "RESET_UI_ONLY" });

    const id = setTimeout(() => {
      setFormKey((previous) => previous + 1);
      dispatch({ type: "SET_BUTTON_TEXT", text: "booking.checkAvailability" });
    }, 4000);

    return () => clearTimeout(id);
  }, [actionResult, dispatch, setFormKey]);

  useEffect(() => {
    const currentState = stateReference.current;
    if (currentState && !currentState["success"] && currentState["errors"]) {
      dispatch({ type: "SET_CAPTCHA", token: "" });
      recaptchaReference.current?.reset();
      const firstError = document.querySelector('[aria-invalid="true"]');
      firstError?.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }, [actionResult]);

  const perks = [
    { id: "experts", text: t("booking.perkLocalExperts", "Licensed local drivers & guides") },
    { id: "flexible", text: t("booking.perkFlexible", "Flexible departures from Marrakech") },
    { id: "support", text: t("booking.perkSupport", "Fast responses within 24 hours") },
  ];

  const selectedTour =
    tourTitle && tourId ?
      `${tourTitle} - Duration: ${
        TOURS_DATA.find((t) => t.id === Number(tourId))?.duration || ""
      } Days`
    : tourTitle || excursionTitle || "";

  const tourDuration =
    tourId ? (TOURS_DATA.find((t) => t.id === Number(tourId))?.duration ?? null) : null;

  return (
    <section
      id="booking"
      aria-labelledby="booking-heading"
      className={`bg-neutral-50 py-20 md:py-10 ${fullWidth ? "booking-form-fullwidth" : ""}`}
    >
      <div
        className={`booking-form-inner mx-auto overflow-x-hidden inline-full max-inline-6xl ${fullWidth ? "px-4 sm:px-6 lg:px-10" : "px-4 sm:px-6 lg:px-8"}`}
      >
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-5">
          <div
            className="inline-full lg:col-span-3"
            data-animate="creative-slide-right"
          >
            <div className="overflow-hidden rounded-3xl bg-white block-full">
              <div className="bg-linear-to-r from-orange-500 to-orange-600 px-6 py-8 text-white">
                <h2
                  className="text-xl font-semibold sm:text-2xl md:text-3xl"
                  id="booking-heading"
                >
                  {t("booking.makeReservation", "Make your reservation")}
                </h2>
                <p className="mbs-3 text-sm text-orange-50/90 md:text-base">
                  {t("booking.description", "Book your perfect Morocco adventure with us")}
                </p>
              </div>

              <form
                key={formKey}
                action={formAction}
                className="space-y-5 p-6 md:p-8"
                noValidate
                data-form="booking"
              >
                <FormStatusMessages
                  submitError={state?.["errors"]?.["submit"]}
                  success={state?.["success"]}
                  successMessage={state?.["message"]}
                />

                <div
                  aria-hidden="true"
                  className="absolute -left-2499.75 h-0 overflow-hidden"
                >
                  <input
                    type="text"
                    name="website"
                    tabIndex={-1}
                    autoComplete="off"
                    aria-label="Leave this field empty"
                  />
                </div>

                <BookingFormFields
                  state={state}
                  selectedTour={selectedTour}
                  tourTitle={tourTitle}
                  tourId={tourId}
                  tourDuration={tourDuration}
                  excursionTitle={excursionTitle}
                  excursionId={excursionId}
                  locale={i18n.language}
                  calendarOpen={uiState.calendarOpen}
                  reservationDate={uiState.reservationDate}
                  onCalendarOpenChange={(open) => dispatch({ type: "SET_CALENDAR_OPEN", open })}
                  onDateSelect={(date) => dispatch({ type: "SET_DATE", date })}
                />

                <div className="flex flex-col gap-4 lg:flex-row lg:items-center">
                  <div className="flex justify-center inline-full lg:justify-start">
                    <div
                      className={cn(
                        "w-fit origin-center scale-85 rounded-2xl border border-dashed p-3 transition-all duration-500 sm:scale-100",
                        state?.["errors"]?.["recaptchaToken"] ?
                          "border-red-300"
                        : "border-neutral-200",
                      )}
                    >
                      {hasRecaptchaV2 ?
                        <Suspense
                          fallback={
                            <div className="rounded-lg bg-amber-50 p-2 text-sm text-amber-600">
                              Loading reCAPTCHA...
                            </div>
                          }
                        >
                          <ReCAPTCHA
                            ref={recaptchaReference}
                            sitekey={RECAPTCHA_V2_SITE_KEY}
                            onChange={(token: string | null) =>
                              dispatch({ type: "SET_CAPTCHA", token: token || "" })
                            }
                          />
                          <input
                            type="hidden"
                            name="recaptchaToken"
                            value={uiState.captchaToken}
                          />
                        </Suspense>
                      : <div className="rounded-lg bg-amber-50 p-2 text-sm text-amber-600">
                          reCAPTCHA not configured
                        </div>
                      }
                    </div>
                  </div>
                  {state?.["errors"]?.["recaptchaToken"] ?
                    <p
                      id="recaptchaToken-error"
                      className="mbs-1 text-xs text-red-600"
                    >
                      {state["errors"]["recaptchaToken"]}
                    </p>
                  : null}
                  <SubmitButton buttonText={uiState.buttonText} />
                </div>
              </form>
            </div>
          </div>

          <div
            className="inline-full lg:col-span-2 lg:block-full"
            data-animate="creative-slide-left"
            data-delay="150"
          >
            <BookingSidebar perks={perks} />
          </div>
        </div>
      </div>
    </section>
  );
}

export default BookingForm;
